### ISSUE TITLE
Error on open file in ubuntu linux

### ISSUE THREAD

**Issue by fabioconedera** [dutzi/tamper#16]
Hi,

I'm trying to run Tamper with google chrome on linux. When I try to modify a file from the Develop Tools's Tamber tab, chrome display this error:

[10368:10368:1120/094001:ERROR:CONSOLE(3)] "Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.0/$rootScope/inprog?p0=%24digest
    at chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:1:14925
    at m (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:9654)
    at l.$digest (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:12072)
    at chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/panel.js:1:2610
    at i (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:6354)
    at chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:6526
    at l.$eval (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:13712)
    at l.$digest (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:12208)
    at chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:3:13797
    at g (chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js:2:1339)", source: chrome-extension://mabhojhgigkmnkppkncbkblecnnanfmd/scripts/vendor.js (3)

**Comment by a904guy** [comment]
This can be closed. Confirmed local modifications work.

![2015-06-14_14 47 11_selection_1134x1076_afbc](https://cloud.githubusercontent.com/assets/404081/8149928/465b86e4-12a4-11e5-8f90-fa9a5b77fbc5.png)

**Comment by DennisJamin** [comment]
I'm experiencing the same issue on Mac OSX and receive the same error as stated in the original message.

OS X Yosemite 10.10.3
Chrome 43.0.2357.132 (64-bit)
