### ISSUE TITLE
Linux cannot connect to proxy.

### ISSUE THREAD

**Issue by a904guy** [dutzi/tamper#28]
Here is what I'm seeing. Ubuntu 14.04, Python 2.7.8.

```
➜  ~  tamper.py        


^CTraceback (most recent call last):
  File "/usr/local/bin/tamper.py", line 345, in <module>
    main(sys.argv)
  File "/usr/local/bin/tamper.py", line 341, in main
    time.sleep(1)
KeyboardInterrupt
➜  ~  tamper.py -p 4187
Traceback (most recent call last):
  File "/usr/local/bin/tamper.py", line 345, in <module>
    main(sys.argv)
  File "/usr/local/bin/tamper.py", line 338, in main
    start_server(int(argv[2]))
  File "/usr/local/bin/tamper.py", line 53, in start_server
    port = int(port)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/config.py", line 86, in __init__
    CONF_BASENAME)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 207, in from_store
    dh = cls.load_dhparam(dh_path)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 181, in load_dhparam
    bio = OpenSSL.SSL._lib.BIO_new_file(path, b"r")
AttributeError: 'module' object has no attribute '_lib'
```

I'll do more debugging later, see if I can fix it.

**Comment by a904guy** [comment]
Compiling from source netlib resolves the issue. netstat shows tamper.py listening.

The interface still says no proxy. Will continue debugging.

~@
