### ISSUE TITLE
cannot install tamper on python 3.7 (macsox)

### ISSUE THREAD

**Issue by uriel-sf** [dutzi/tamper#51]
* followed the wiki to properly install python: [Troubleshooting · dutzi/tamper Wiki · GitHub](https://github.com/dutzi/tamper/wiki/Troubleshooting) 
* ran `pip install tamper`
* Got this error:

```
Collecting tamper
  Using cached tamper-0.24.5.tar.gz (6.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rs/x46xkw452yl8xzdvkhqbzsgh0000gn/T/pip-install-5m8nd9z1/tamper/setup.py'"'"'; __file__='"'"'/private/var/folders/rs/x46xkw452yl8xzdvkhqbzsgh0000gn/T/pip-install-5m8nd9z1/tamper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rs/x46xkw452yl8xzdvkhqbzsgh0000gn/T/pip-install-5m8nd9z1/tamper/pip-egg-info
         cwd: /private/var/folders/rs/x46xkw452yl8xzdvkhqbzsgh0000gn/T/pip-install-5m8nd9z1/tamper/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rs/x46xkw452yl8xzdvkhqbzsgh0000gn/T/pip-install-5m8nd9z1/tamper/setup.py", line 60
        print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'
                                                                ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by scil** [comment]
same error on windows. python3.7.

**Comment by wwwDayDream** [comment]
Same problem on windows, 3.7 Shame. Any resolve?

**Comment by wiwitadityasaputra** [comment]
same error

**Comment by FritzHerbers** [comment]
@dutzi 
The error does not exist on Linux, but exists on Windows (macosx from OP).

on Linux Ubuntu, the chrome extension does not install (the error is not explanatory).

**Comment by erickmoreno** [comment]
I can confirm the same error on Linux Ubuntu, python 3.8 and pip 20.1.1

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

$ pip --version
pip 20.1.1 from /usr/lib/python3/dist-packages/pip (python 3.8)

$ pip install tamper
Collecting tamper
  Using cached tamper-0.24.5.tar.gz (6.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g71pweod/tamper/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g71pweod/tamper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l4to5xzr
         cwd: /tmp/pip-install-g71pweod/tamper/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g71pweod/tamper/setup.py", line 60
        print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'
              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by iyxan23** [comment]
It's because tamper is written in python 2, this repo is really old and never got updated.

**Comment by dutzi** [comment]
Yeah, sorry about that. I did try fixing it, but Chrome's Native Messaging API is so bad I couldn't.
